###################  spring配置  ###################
spring:
   profiles:
     active: dev
   http:
#     multipart:
#       max-request-size: 10MB
#       max-file-size: 10MB
     encoding:
       force: true
       enabled: true
       charset: utf-8

server:
  undertow:
    io-threads: 100
    worker-threads: 200
    buffer-size: 1024
    direct-buffers: true

#  session:
#    cookie:
#      http-only: true